[general]
import = ["/home/rae/.config/alacritty/themes/thelovelace.toml"]

[terminal]
shell = "/home/rae/.cargo/bin/nu"

[window]
opacity = 0.8
blur = false
padding = { x = 15, y = 15 }

[font]
size = 11
normal = {family = "CommitMonoNerdFont Mono", style = "Regular"}
bold = {family = "CommitMonoNerdFont Mono", style = "Bold"}
italic = {family = "CommitMonoNerdFont Mono", style = "Italic"}
bold_italic = {family = "CommitMonoNerdFont Mono", style = "Bold Italic"}
